db_username=postgres
db_password=424242
db_url=db
db_name=tasks
# r2dbc_url=r2dbc:postgresql://postgres:424242@db:5432/tasks
r2dbc_url=r2dbc:postgresql://${db_username}:${db_password}@${db_url}:5432/${db_name}