/*
 * This file is generated by jOOQ.
 */
package ru.spbstu.ai.r2dbc.db.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import ru.spbstu.ai.r2dbc.db.Keys;
import ru.spbstu.ai.r2dbc.db.Public;
import ru.spbstu.ai.r2dbc.db.tables.RecurringTask.RecurringTaskPath;
import ru.spbstu.ai.r2dbc.db.tables.Task.TaskPath;
import ru.spbstu.ai.r2dbc.db.tables.records.OwnerRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Owner extends TableImpl<OwnerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.owner</code>
     */
    public static final Owner OWNER = new Owner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OwnerRecord> getRecordType() {
        return OwnerRecord.class;
    }

    /**
     * The column <code>public.owner.owner_id</code>.
     */
    public final TableField<OwnerRecord, Integer> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.owner.telegram_id</code>.
     */
    public final TableField<OwnerRecord, Integer> TELEGRAM_ID = createField(DSL.name("telegram_id"), SQLDataType.INTEGER, this, "");

    private Owner(Name alias, Table<OwnerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Owner(Name alias, Table<OwnerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.owner</code> table reference
     */
    public Owner(String alias) {
        this(DSL.name(alias), OWNER);
    }

    /**
     * Create an aliased <code>public.owner</code> table reference
     */
    public Owner(Name alias) {
        this(alias, OWNER);
    }

    /**
     * Create a <code>public.owner</code> table reference
     */
    public Owner() {
        this(DSL.name("owner"), null);
    }

    public <O extends Record> Owner(Table<O> path, ForeignKey<O, OwnerRecord> childPath, InverseForeignKey<O, OwnerRecord> parentPath) {
        super(path, childPath, parentPath, OWNER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OwnerPath extends Owner implements Path<OwnerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OwnerPath(Table<O> path, ForeignKey<O, OwnerRecord> childPath, InverseForeignKey<O, OwnerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OwnerPath(Name alias, Table<OwnerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OwnerPath as(String alias) {
            return new OwnerPath(DSL.name(alias), this);
        }

        @Override
        public OwnerPath as(Name alias) {
            return new OwnerPath(alias, this);
        }

        @Override
        public OwnerPath as(Table<?> alias) {
            return new OwnerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OwnerRecord, Integer> getIdentity() {
        return (Identity<OwnerRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OwnerRecord> getPrimaryKey() {
        return Keys.OWNER_PKEY;
    }

    private transient RecurringTaskPath _recurringTask;

    /**
     * Get the implicit to-many join path to the
     * <code>public.recurring_task</code> table
     */
    public RecurringTaskPath recurringTask() {
        if (_recurringTask == null)
            _recurringTask = new RecurringTaskPath(this, null, Keys.RECURRING_TASK__RECURRING_TASK_OWNER_ID_FKEY.getInverseKey());

        return _recurringTask;
    }

    private transient TaskPath _task;

    /**
     * Get the implicit to-many join path to the <code>public.task</code> table
     */
    public TaskPath task() {
        if (_task == null)
            _task = new TaskPath(this, null, Keys.TASK__TASK_OWNER_ID_FKEY.getInverseKey());

        return _task;
    }

    @Override
    public Owner as(String alias) {
        return new Owner(DSL.name(alias), this);
    }

    @Override
    public Owner as(Name alias) {
        return new Owner(alias, this);
    }

    @Override
    public Owner as(Table<?> alias) {
        return new Owner(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Owner rename(String name) {
        return new Owner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Owner rename(Name name) {
        return new Owner(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Owner rename(Table<?> name) {
        return new Owner(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owner where(Condition condition) {
        return new Owner(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owner where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owner where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owner where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owner where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owner where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owner where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owner where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owner whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owner whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
