/*
 * This file is generated by jOOQ.
 */
package ru.spbstu.ai.r2dbc.db;


import ru.spbstu.ai.r2dbc.db.tables.Owner;
import ru.spbstu.ai.r2dbc.db.tables.RecurringTask;
import ru.spbstu.ai.r2dbc.db.tables.Task;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.owner</code>.
     */
    public static final Owner OWNER = Owner.OWNER;

    /**
     * The table <code>public.recurring_task</code>.
     */
    public static final RecurringTask RECURRING_TASK = RecurringTask.RECURRING_TASK;

    /**
     * The table <code>public.task</code>.
     */
    public static final Task TASK = Task.TASK;
}
